-- Supabase Schema for Bobsleigh Coach AI

-- Users table is managed by Supabase Auth

-- Athletes table
CREATE TABLE athletes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    sport TEXT NOT NULL,
    height FLOAT,
    weight FLOAT,
    birth_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add row level security policies for athletes
ALTER TABLE athletes ENABLE ROW LEVEL SECURITY;

-- Allow users to view/edit their own athlete profiles
CREATE POLICY "Users can view their own profiles" 
    ON athletes FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own profiles" 
    ON athletes FOR UPDATE 
    USING (auth.uid() = user_id);

-- Exercises table
CREATE TABLE exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT,
    measurement_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add row level security policies for exercises
ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to view exercises
CREATE POLICY "Authenticated users can view exercises" 
    ON exercises FOR SELECT 
    TO authenticated 
    USING (true);

-- Workouts table
CREATE TABLE workouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id BIGINT REFERENCES athletes(id) NOT NULL,
    name TEXT NOT NULL,
    date DATE NOT NULL,
    duration INTEGER,
    type TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add row level security policies for workouts
ALTER TABLE workouts ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own workouts
CREATE POLICY "Users can view their own workouts" 
    ON workouts FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM athletes 
            WHERE athletes.id = workouts.athlete_id 
            AND athletes.user_id = auth.uid()
        )
    );

-- Allow users to insert their own workouts
CREATE POLICY "Users can insert their own workouts" 
    ON workouts FOR INSERT 
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM athletes 
            WHERE athletes.id = workouts.athlete_id 
            AND athletes.user_id = auth.uid()
        )
    );

-- Allow users to update their own workouts
CREATE POLICY "Users can update their own workouts" 
    ON workouts FOR UPDATE 
    USING (
        EXISTS (
            SELECT 1 FROM athletes 
            WHERE athletes.id = workouts.athlete_id 
            AND athletes.user_id = auth.uid()
        )
    );

-- Workout exercises table
CREATE TABLE workout_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id BIGINT REFERENCES workouts(id) NOT NULL,
    exercise_id BIGINT REFERENCES exercises(id) NOT NULL,
    sets INTEGER,
    reps INTEGER,
    weight FLOAT,
    distance FLOAT,
    time FLOAT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add row level security policies for workout exercises
ALTER TABLE workout_exercises ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own workout exercises
CREATE POLICY "Users can view their own workout exercises" 
    ON workout_exercises FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM workouts 
            JOIN athletes ON workouts.athlete_id = athletes.id 
            WHERE workout_exercises.workout_id = workouts.id 
            AND athletes.user_id = auth.uid()
        )
    );

-- Allow users to insert their own workout exercises
CREATE POLICY "Users can insert their own workout exercises" 
    ON workout_exercises FOR INSERT 
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM workouts 
            JOIN athletes ON workouts.athlete_id = athletes.id 
            WHERE workout_exercises.workout_id = workouts.id 
            AND athletes.user_id = auth.uid()
        )
    );

-- Workout exercise sets table
CREATE TABLE workout_exercise_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_exercise_id BIGINT REFERENCES workout_exercises(id) NOT NULL,
    set_number INTEGER NOT NULL,
    reps INTEGER,
    weight FLOAT,
    distance FLOAT,
    time FLOAT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add row level security policies for workout exercise sets
ALTER TABLE workout_exercise_sets ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own workout exercise sets
CREATE POLICY "Users can view their own workout exercise sets" 
    ON workout_exercise_sets FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM workout_exercises 
            JOIN workouts ON workout_exercises.workout_id = workouts.id 
            JOIN athletes ON workouts.athlete_id = athletes.id 
            WHERE workout_exercise_sets.workout_exercise_id = workout_exercises.id 
            AND athletes.user_id = auth.uid()
        )
    );

-- Performance metrics table
CREATE TABLE performance_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id BIGINT REFERENCES athletes(id) NOT NULL,
    date DATE NOT NULL,
    metric_type TEXT NOT NULL,
    metric_name TEXT NOT NULL,
    value FLOAT NOT NULL,
    unit TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add row level security policies for performance metrics
ALTER TABLE performance_metrics ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own performance metrics
CREATE POLICY "Users can view their own performance metrics" 
    ON performance_metrics FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM athletes 
            WHERE athletes.id = performance_metrics.athlete_id 
            AND athletes.user_id = auth.uid()
        )
    );

-- Training loads table
CREATE TABLE training_loads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id BIGINT REFERENCES athletes(id) NOT NULL,
    date DATE NOT NULL,
    training_load FLOAT NOT NULL,
    ctl FLOAT,
    atl FLOAT,
    tsb FLOAT,
    rpe FLOAT,
    fatigue FLOAT,
    soreness FLOAT,
    sleep_quality FLOAT,
    sleep_hours FLOAT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add row level security policies for training loads
ALTER TABLE training_loads ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own training loads
CREATE POLICY "Users can view their own training loads" 
    ON training_loads FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM athletes 
            WHERE athletes.id = training_loads.athlete_id 
            AND athletes.user_id = auth.uid()
        )
    );

-- Training recommendations table
CREATE TABLE training_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id BIGINT REFERENCES athletes(id) NOT NULL,
    date DATE NOT NULL,
    recommendation_date DATE NOT NULL,
    workout_type TEXT NOT NULL,
    focus TEXT NOT NULL,
    duration INTEGER,
    intensity TEXT,
    exercises JSONB,
    notes TEXT,
    is_completed INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add row level security policies for training recommendations
ALTER TABLE training_recommendations ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own training recommendations
CREATE POLICY "Users can view their own training recommendations" 
    ON training_recommendations FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM athletes 
            WHERE athletes.id = training_recommendations.athlete_id 
            AND athletes.user_id = auth.uid()
        )
    );

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add triggers to update updated_at columns
CREATE TRIGGER update_athletes_updated_at
    BEFORE UPDATE ON athletes
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_exercises_updated_at
    BEFORE UPDATE ON exercises
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_workouts_updated_at
    BEFORE UPDATE ON workouts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_workout_exercises_updated_at
    BEFORE UPDATE ON workout_exercises
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_workout_exercise_sets_updated_at
    BEFORE UPDATE ON workout_exercise_sets
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_performance_metrics_updated_at
    BEFORE UPDATE ON performance_metrics
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_training_loads_updated_at
    BEFORE UPDATE ON training_loads
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_training_recommendations_updated_at
    BEFORE UPDATE ON training_recommendations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insert sample exercises
INSERT INTO exercises (name, description, category, measurement_type) VALUES
('Back Squat', 'Barbell squat with weight on upper back', 'Strength', 'Weight'),
('Bench Press', 'Horizontal press with barbell', 'Strength', 'Weight'),
('Deadlift', 'Barbell lift from floor', 'Strength', 'Weight'),
('Power Clean', 'Olympic lift from floor to shoulders', 'Power', 'Weight'),
('30m Sprint', '30 meter sprint', 'Speed', 'Time'),
('60m Sprint', '60 meter sprint', 'Speed', 'Time'),
('Box Jump', 'Jumping onto elevated platform', 'Power', 'Height'),
('Vertical Jump', 'Jump test for vertical height', 'Power', 'Height'),
('Pull-ups', 'Bodyweight pull-up exercise', 'Strength', 'Reps'),
('Push-ups', 'Bodyweight pushing exercise', 'Strength', 'Reps'),
('Romanian Deadlift', 'Hip-hinge deadlift variation', 'Strength', 'Weight'),
('Split Squat', 'Single-leg squat variation', 'Strength', 'Weight'),
('Medicine Ball Throw', 'Explosive throw with medicine ball', 'Power', 'Distance'),
('Broad Jump', 'Horizontal jump test', 'Power', 'Distance'),
('Hill Sprints', 'Sprints performed on an incline', 'Speed', 'Time/Distance'),
('Flying Sprints', 'Sprint with running start', 'Speed', 'Time/Distance'),
('Resisted Sprints', 'Sprints with added resistance', 'Speed', 'Time/Distance');
